### ISSUE TITLE
Which PCL version is required?

### ISSUE THREAD

**Issue by sirackerman** [DioVei/ORB_SLAM3_with_save#3]
Hello , please which pcl version is required? I'm using ubuntu 18.04

**Comment by DioVei** [comment]
I used 1.8, but I think most versions can support it.

**Comment by sirackerman** [comment]
Alright, thank you!

**Comment by sirackerman** [comment]
Hi @DioVei. I have an issue here would like to have if possible, your insight on how to solve it. 
I use Thien ros wrapper to run a modified version of orbslam version I'm working on. The save function works well when I run orbslam as a standalone library. I'd like that function to also work when I use the ros wrapper. I added the point cloud library in the ros wrapper Cmakelist so that it could compile against it and it worked. Now when I run my simulations, it doesnt save the point cloud nor in the ros wrapper folder neither in the orbslam folder. Do you have idea on how I could make it work? I'm thinking about creating a node for that but I'm unsure if it's the right way forward. Thanks in advance for your insight.

**Comment by DioVei** [comment]
Thanks for your question, I'm sorry about that I haven't used ros wrapper yet, so I can't help you, hope you can solve it.

**Comment by sirackerman** [comment]
Will try. thank you for your answer
